version: '3.9'

services:
  app:
    container_name: mooring
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app
      - ./creds.json:/secrets/creds.json
    env_file:
      - ./.env
    restart: always
