# Generated by Django 4.1.6 on 2023-03-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('mooring_no', models.IntegerField()),
                ('mooring_location', models.CharField(max_length=200)),
                ('depth', models.IntegerField()),
                ('last_check', models.DateTimeField()),
            ],
        ),
    ]
