# Generated by Django 4.1.6 on 2023-04-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boats',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='boats',
            name='last_check',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='boats',
            name='mooring_no',
            field=models.CharField(max_length=200),
        ),
    ]
