# Generated by Django 4.1.3 on 2023-04-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_remove_order_boat_image_pre1_order_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='images',
        ),
        migrations.AlterField(
            model_name='boat',
            name='boat_image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='boat',
            name='boat_image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='boat',
            name='boat_image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
