# Generated by Django 4.1.6 on 2023-04-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_boats_image_alter_boats_last_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boats',
            name='image',
            field=models.ImageField(null=True, upload_to='../static/images'),
        ),
    ]
