# Generated by Django 4.1.6 on 2023-04-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0005_alter_boats_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boats',
            name='image',
        ),
        migrations.AddField(
            model_name='boats',
            name='boat_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
